name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# Add these permissions
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4  # Updated version
      
    - name: Setup Node
      uses: actions/setup-node@v4  # Updated version
      with:
        node-version: '18'
        cache: 'npm'  # Added caching
        
    - name: Install dependencies
      run: npm ci  # More reliable than npm install
      
    - name: Build
      run: npm run build
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist